---
- hosts: tag_Environment_dev
  vars:
    vagrant: False
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/mlabs_modus.pem
    clienturl: factualclient.marriottlabs.com
    serverurl: factualserver.marriottlabs.com

  roles: 
    - { role: factualtest }
